#!/bin/sh
THEME='#window { width: 15%; height: 25%; y-offset: 5%; }' 
CONFIGS=$(ls -1 /etc/wireguard | sed -e 's/\..*$//')
LAST=$(cat ~/.cache/wireguard)
ADDRESS=$(awk '/Address/ {print $NF}' "/etc/wireguard/$LAST.conf")
get_status(){
    ping -c 1 -w 2 8.8.8.8 &> /dev/null && (ping -c 1 -w 2 $ADDRESS &>/dev/null && echo "%{T4}  %{T-}%{T2}("$LAST")%{T-} " || echo "%{T4}  %{T-} ") || echo  "%{T4}  %{T-} "
}
connect(){
    wg-quick up "$LAST"
}

disconnect(){
    wg-quick down "$LAST"
}
show_menu(){
            chosen="$(echo -e "connect($LAST)\ndisconnect\nswitch" | rofi -dmenu -location 3 -theme-str "$THEME" -i -p 'Wireguard VPN' )"
            case $chosen in
                "connect($LAST)" )
                    connect ;;
                "disconnect" )
                    disconnect ;;
                "switch" )
                    chosen="$(echo "$CONFIGS" | rofi -dmenu -location 3 -theme-str "$THEME" -i -p 'Wireguard VPN' )"
                    if wg; then
                        wg-quick up $chosen
                    else
                        disconnect
                        wg-quick up $chosen
                    fi
                    echo "$chosen" > ~/.cache/wireguard
                    ;;
            esac
}

while getopts 'smcdt' arg
do
    case $arg in
        "s" )
            get_status ;;
        "m" )
            show_menu ;;
        "c" )
            connect ;;
        "d" )
            disconnect ;;
        "t" )
            ip a | grep POINTOPOINT &> /dev/null && disconnect || connect
            ;;
    esac
    
done
