#!/bin/sh
THEME='#window { width: 15%; height: 25%; y-offset: 5%; }' 
COUNTRIES=$(ls -1 /etc/wireguard | sed -e 's/\..*$//')
LAST=$(cat ~/.cache/wireguard)

if [ $# -eq 0 ] 
then
    ping -c 1 -w 2 8.8.8.8 &> /dev/null && (ping -c 1 -w 2 10.6.0.1 &>/dev/null && echo " " || echo " ") || echo " "
else
    case $1 in
        "change" )
            chosen="$(echo -e "connect($LAST)\ndisconnect\nswitch" | rofi -dmenu -location 3 -theme-str "$THEME" -i -p 'Wireguard VPN' )"
            case $chosen in
                "connect($LAST)" )
                    wg-quick up "$LAST" ;;
                "disconnect" )
                    wg-quick down "$LAST" ;;
                "switch" )
                    chosen="$(echo "$COUNTRIES" | rofi -dmenu -location 3 -theme-str "$THEME" -i -p 'Wireguard VPN' )"
                    wg-quick up $chosen
                    echo "$chosen" > ~/.cache/wireguard
                    ;;
            esac
            ;;
        "connect" )
            wg-quick up $LAST ;;
        "disconnect" )
            wg-quick down $LAST ;;
        "toggle" )
            ip a | grep POINTOPOINT &> /dev/null && wg-quick down $LAST || wg-quick up $LAST
    esac

fi
